### ISSUE TITLE
Refactor naming 

### ISSUE THREAD

**Issue by sibille** [microsoft/CoreTemplateStudio#101]
Action Plan: 

- [x] Review naming / validation code to see what should be done where (see comments below)
- [x] Build Services for Project Name validation
- [x] Build Services for Item Name validation
- [x] Validate names before Generation

**Comment by dgomezc** [comment]
Currently validation of project / item names is only done in the UI, we should do them in UI and re-validate in Core before generation.

Currently we are doing the following validations:

Validations on project names:

- ProjectStartWith (Regex)
- ProjectReservedNames (List of names)

Validation on item name:

- Bad Format (Regex)
- EmptyName (Regex)
- PageSuffix (Regex)
- DefaultName (List of defaultnames extracted from available templates)
- ReservedNames (List of names)
- ExistingNames (no duplicated names on userSelection)

Is there anything else we should validate?

Regex and reserved names depend on the platform (Uwp or Web) so they should not be "hardcoded" in the core, but configurable in templates.

Plan is to do a config file for projects and items, that is used to configure the different validators.

Sample project name validation config file:

```javascript
"projectValidations" : [
  "regexValidations" : [
    {
      "name" : "projectStartWithValidation",
      "expression" : " ... regex_expresion_to_validate_start_with_$_char"
    }
  ],
  "reservedProjectNamesValidator" : [
    "Prism",
    "CaliburnMicro",
    "MVVMLight"
  ]
]

```
Sample item name validation config file:

```javascript
"itemsValidations" : [
  "regexValidations" : [
    {
      "name" : "badFormatValidation",
      "expression" : "^((?!\\d)\\w+)$"
    },
    {
      "name" : "pageSuffixValidator",
      "expression" : "... regex_expresion_to_validate_end_with_PAGE"
    }
  ],
  "reservedItemNamesValidator" : [
    "Page",
    "BackgroundTask",
    "Pivot",
    "Shell",
    "User",
    "LogIn",
    "SharedDataWebLink",
    "SharedDataStorageItems",
    "SchemeActivationSample"
  ],
  "defaultNamesValidator" : true,
  "emptyNameValidator" : true,
  "existingNames  Validator" : true
]
```

For WinTS same validators can be used from UI and Core, on WebTS the validation config is returned on Template Sync, so validation can be done on the client with the same ruleset as CoreTS will apply before generation.

**Comment by sibille** [comment]
Name validators should return all validation errors
