### ISSUE TITLE
Improve reasoning for CoreTS failing in CLI

### ISSUE THREAD

**Issue by SahilTara** [Microsoft/CoreTemplateStudio#180]
Error executing Command: sync -p ../../../../...
One or more errors occurred. (Error syncing templates. Object reference not set to an instance of an object.)

Currently if I do `chmod 444 ~/.local/share` to simulate lack of permissions the above error message is all I get from CoreTs.  (Do `chmod 755 ~/.local/share` to reset permissions to default after reproducing.) 

Note: Doing this on a Mac to simulate permissions, but can be done on windows or linux based os as well. 

I think we need more specific error messages to handle cases like this.

**Comment by dgomezc** [comment]
Same happen for failing postactions.

**Comment by sibille** [comment]
Verified in WebTS dev
