### ISSUE TITLE
Will package download and verification support be added?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/CoreTemplateStudio#238]
The main readme currently lists the following limitation:

> Currently does not support Package download and verification from the CDN.

There appears to be no open issue to track this. Is it planned?

**Comment by sibille** [comment]
Yes, tracking issue is https://github.com/microsoft/CoreTemplateStudio/issues/131
Will add more info there and also update the main readme, as this is only true for WebTS, not WinTS, which supports package download and verification.

**Comment by mvegaca** [comment]
Verified in dev
