### ISSUE TITLE
Document branching strategy

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/CoreTemplateStudio#239]
There are now two branches [dev](https://github.com/microsoft/CoreTemplateStudio/tree/dev) (the default) and [release](https://github.com/microsoft/CoreTemplateStudio/tree/release).
However, there are no formal releases as both WindowsTemplateStudio and WebTemplateStudio access this functionality as git sub-modules.
With no formal releases, it's not clear how each branch is, will, or should be used.

**Comment by sibille** [comment]
There is no release of CoreTS as a standalone product but as part of WebTS and WinTS so referencing the release branch seemed more adecuate than pointing from the release branches of WebTS and WinTS to CoreTS dev. It also gives us the flexibility to bring new functionality to CoreTS dev and test it from WebTS and WinTS in an easier way before merging to release.

Will add documentation for this to developer documents.

**Comment by sibille** [comment]
Verified in dev
