### ISSUE TITLE
Fix warning about missing Mono.Posix refrence

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/CoreTemplateStudio#240]
The source reports a (10!) warning(s) about being unable to find a reference to Mono.Posix.
Warnings should be fixed on the broken windows principle, and because they risk obscuring other warnings.

This warning is due to a dependency included in CoreTS so that it can run on platforms beyond Windows.

**Comment by sibille** [comment]
I opted for the OS condition as this is only needed on OS different from Windows. 
Adding this a as a private assembly would require adding it to the CoreTSCli too.
