### ISSUE TITLE
Add posibilty to lower case in wts.casing tag

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/CoreTemplateStudio#243]
Add posibilty use lower case in wts.casing tag

**Comment by sibille** [comment]
The dotnet templating engine's toLower casing generator does not allow to use toLower on SourceName yet.(https://github.com/dotnet/templating/issues/2210).

**Comment by sibille** [comment]
Usage sample: 
- Add tag: `"wts.casing.sourceName": "lower"`
- Add parameter: 
```
"wts.sourceName.casing.lower": {
      "type": "parameter",
      "replaces": "Param_SourceName_Lower",
      "fileRename":"Param_SourceName_Lower"
    }
```

**Comment by sibille** [comment]
Verified in dev
