### ISSUE TITLE
Review and update nuget packages in Core

### ISSUE THREAD

**Issue by sibille** [Microsoft/CoreTemplateStudio#270]
New versions are available for the following packages used in Core, we should update to the latest version: 
- [x] ApplicationInsights
- [x] Newtonsoft.Json (update to version 12.0.2 which is shipped with VS 2019 https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/)
- [x] StyleCop
- [x] ConfigurationManager
- [x] System.IO.Packaging

**Comment by mvegaca** [comment]
Verified in dev
