### ISSUE TITLE
Add React Native as platform

### ISSUE THREAD

**Issue by sibille** [Microsoft/CoreTemplateStudio#276]
We need to add React Native as a platform for https://github.com/microsoft/WebTemplateStudio/issues/1662

**Comment by mrlacey** [comment]
I know I've brought this up before, but it seems odd that CoreTS needs to know about supported platforms.
Doesn't this indicate a poor separation between what's "core" what consumes the "core" library?
There appears to be a cyclical link between something that uses CoreTS and it needing to have information about what the things that use it want to do.

**Comment by sibille** [comment]
CoreTS is platform and language agnostic, but it's where Platforms and Languages are defined and validated (due to how things grew in the past).
We should split and move the Platforms and ProgrammingLanguages classes and move them to WebTS + WinTS.

**Comment by sibille** [comment]
Created a separate issue for splitting and moving the Platform and ProgrammingLanguages classes in https://github.com/microsoft/CoreTemplateStudio/issues/282

**Comment by prupipho** [comment]
Tested on nightly build:
Templates version: 0.3.21113.4
Wizard version: 0.3.2111304
