### ISSUE TITLE
 Bug: Defining all in project wts.projecttypes does not return any projecttypes

### ISSUE THREAD

**Issue by sibille** [Microsoft/CoreTemplateStudio#279]
Defining all in a projects templates tag "wts.projecttypes" does not return any projecttypes.
Projecttypes have to be defined explicitly to get results. 
We should change this, all project types should be returned in this case.

**Comment by prupipho** [comment]
Tested on WebTemplateStudio dev branch

**Comment by prupipho** [comment]
Working on dev after updating templates to do this.
