### ISSUE TITLE
Migrate to Microsoft.CodeAnalysis.NetAnalyzers analyzers

### ISSUE THREAD

**Issue by sibille** [Microsoft/CoreTemplateStudio#281]
Post-build Code Analysis (FxCopCmd.exe) has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers.

**Comment by sibille** [comment]
Microsoft.CodeAnalysis.FxCopAnalyzers were deprecated in favor of Microsoft.CodeAnalysis.NetAnalyzers. We'll update to Microsoft.CodeAnalysis.NetAnalyzers directly.

**Comment by dgomezc** [comment]
Verified in dev
