### ISSUE TITLE
Change image path in Core Template Studio API to relative path to templates once the Core is functional

### ISSUE THREAD

**Issue by dandua98** [microsoft/CoreTemplateStudio#3]
Update the image path in Core Template Studio API to actual paths relative to the local templates directory after CoreTemplateStudio.Core itself is done and migrated to .NET core. This would be done while migrating the API from bare bones to actually interacting with the Core

**Comment by sibille** [comment]
Closing as this was done by reading the images in the extension as part of https://github.com/microsoft/WebTemplateStudio/issues/1376
