### ISSUE TITLE
Need to connect GetProjectTypes, GetFrameworks and GetPages

### ISSUE THREAD

**Issue by SahilTara** [microsoft/CoreTemplateStudio#47]
- [x] Modify FrameworkController to connect to engine
- [x] Add ability to filter frameworks by type (Frontend and backend)
- [x] Modify ProjectTypeController to connect to engine
- [x] Modify PagesController to connect to engine
- [ ] Create tests for ProjectTypes endpoint
- [ ] Create tests for framework endpoint
- [ ] Create tests for pages end point

**Comment by sibille** [comment]
Closed in favor of https://github.com/microsoft/CoreTemplateStudio/issues/135
