### ISSUE TITLE
Need to connect GetFeatures and Generation endpoint

### ISSUE THREAD

**Issue by SahilTara** [microsoft/CoreTemplateStudio#51]
- [x] Modify Get Features to Connect to the engine
- [x] Modify Generation endpoint to connect to the engine
- [ ] Create tests from Get Features endpoint
- [ ] Create tests from Generation endpoint

**Comment by sibille** [comment]
Closed in favor of https://github.com/microsoft/CoreTemplateStudio/issues/135
